---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/grafana/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana-operator
      interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Default values for the Grafana Operator
    replicaCount: 1
    
    # Enable monitoring of CRDs
    enableMonitoring: true
    
    # Default resource requests and limits
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    # Configure logging
    logLevel: info
    
    # Security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
    
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
